#!/bin/bash

########################## Var Init
resize
declare -A carte

########################## Color & Font

export ETG=$1

############################ Fonction
function InitCarte() {
	export MAP="./data/dungeon/${ETG}.map"
	export CSV="./data/level/${ETG}.csv"
}

function CaraFich() {
	
}
############################## Main ##############################
InitCarte "${carte[@]}"


exit 0