#!/bin/bash

########################## Var Init
resize
declare -A carte
msg=""

########################## Color & Font
export R_COLOR="\033[00m"
export T_NOIR="\033[30m"
export T_ROUGE="\033[31m"
export T_VERT="\033[32m"
export T_ORANGE="\033[33m"
export T_BLEU="\033[34m"
export T_MAGENTA="\033[35m"
export T_CYAN="\033[36m"
export T_BLANC="\033[37m"
export F_NOIR="\033[40m"
export F_ROUGE="\033[41m"
export F_VERT="\033[42m"
export F_ORANGE="\033[43m"
export F_BLEU="\033[44m"
export F_MAGENTA="\033[45m"
export F_CYAN="\033[46m"
export F_BLANC="\033[47m"
export T_GRAS="\033[01m"
export T_GRISE="\033[02m"
export T_ITAL="\033[03m"
export T_SOUL="\033[04m"
export T_CLIGN="\033[05m"
export T_SURLIGNE="\033[07m"
export T_MASQUE="\033[08m"
export T_BARRE="\033[09m"

########################## BackGround
export VIDE="."
export PJ="${T_GRAS}${T_CLIGN}${T_CYAN}@${R_COLOR}"
export NPC="${T_GRAS}${T_ORANGE}@${R_COLOR}"
export BORDMAP="${T_GRAS}${T_BLEU}#${R_COLOR}"

############################ Fonction ############################
function InitCarte(){
	xmax=$((LINES - 15))
	ymax=$((COLUMNS - 50))
	xpos=4
	ypos=4

	for x in $(seq 0 "$xmax"); do
       		for y in $(seq 0 "$ymax"); do
                	if [ "$x" -eq 0 ] || [ "$x" -eq $xmax ] || [ "$y" -eq 0 ] || [ "$y" -eq $ymax ]; then
                        	carte[$x,$y]=$BORDMAP
                	else
                        	carte[$x,$y]=$VIDE
                	fi
        	done
	done
	carte[$xpos,$ypos]=$PJ
}
function Affichage() {
        clear
        for x in $(seq 0 "$xmax"); do
                tmpligne=""
                for y in $(seq 0 "$ymax"); do
                        tmpligne+=${carte[$x,$y]}
                done
                echo -e "$tmpligne"
        done
	echo -e "\nactions [z-up]  [s-down]  [q-left]  [d-right]  [m-quit]"
	echo -e "=> ${msg}"
}
function Game() {
        Affichage "${carte[@]}"
	while :
	do
        	read -r -t 1 -n 1 key
        	if [[ $key = m ]]; then
                	break
        	elif [[ $key = z ]]; then
			if [[ ${carte[$((xpos - 1)),$ypos]} = "$VIDE" ]]; then
				msg="You go to UP"
                		carte[$xpos,$ypos]=$VIDE
                		xpos=$((xpos - 1))
				carte[$xpos,$ypos]=$PJ
			else
				msg="no way"
			fi
                	Affichage "${carte[@]}" "${msg}"
        	elif [[ $key = s ]]; then
			if [[ ${carte[$((xpos + 1)),$ypos]} = "$VIDE" ]]; then
				msg="You go to DOWN"
                		carte[$xpos,$ypos]=$VIDE
                		xpos=$((xpos + 1))
                		carte[$xpos,$ypos]=$PJ
			else
				msg="no way"
			fi
                	Affichage "${carte[@]}" "${msg}"
        	elif [[ $key = q ]]; then
			if [[ ${carte[$xpos,$((ypos - 1))]} = "$VIDE" ]]; then
				msg="You go to LEFT"
                		carte[$xpos,$ypos]=$VIDE
                		ypos=$((ypos - 1))
                		carte[$xpos,$ypos]=$PJ
			else
				msg="no way"
			fi
                	Affichage "${carte[@]}" "${msg}"
        	elif [[ $key = d ]]; then
			if [[ ${carte[$xpos,$((ypos + 1))]} = "$VIDE" ]]; then
				msg="You go to RIGHT"
                		carte[$xpos,$ypos]=$VIDE
                		ypos=$((ypos + 1))
                		carte[$xpos,$ypos]=$PJ
			else
				msg="no way"
			fi
                	Affichage "${carte[@]}" "${msg}"
        	fi
	done
}

############################## Main ##############################
InitCarte "${carte[@]}"
Game "${carte[@]}"

exit 0
